[package]
name = "arc"
version = "0.1.0"
authors = ["J. N. <noehles@easybill.de>"]
edition = "2018"

[dependencies]
native-windows-gui = "1.0.4"
native-windows-derive = "1.0.1"
reqwest = { version = "0.10.8", features = ["blocking"] }